services:

  wargos:
    container_name: wargos
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=true
      # Replace with your `wled` IP addresses
      - WLED_IP_LIST=10.0.1.129,10.0.1.150,10.0.1.179,10.0.1.153
    ports:
      - "9395:9395"
    stdin_open: true
    tty: true
