services:

  wargos:
    container_name: wargos
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=true
      # Replace with your `wled` IP addresses
      - WLED_IP_LIST=10.0.1.129,10.0.1.150,10.0.1.179,10.0.1.153
      # Gunicorn configuration
      - PORT=${PORT:-9395}
      - WORKERS=${WORKERS:-4}
      - TIMEOUT=${TIMEOUT:-120}
      - KEEPALIVE=${KEEPALIVE:-2}
      - MAX_REQUESTS=${MAX_REQUESTS:-1000}
      - MAX_REQUESTS_JITTER=${MAX_REQUESTS_JITTER:-50}
      # Prometheus multiprocess configuration
      - PROMETHEUS_MULTIPROC_DIR=/tmp
      - ENABLE_METRICS=true
    ports:
      - "${PORT:-9395}:${PORT:-9395}"
    stdin_open: true
    tty: true
