services:

  wargos:
    container_name: wargos
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Include this to persist config and presets backups outside of container (across restarts, upgrades)
    volumes:
      - wargos-storage:/backups
    environment:
      - DEBUG=true
      # Replace with your `wled` IP addresses
      - WLED_IP_LIST=10.0.1.129,10.0.1.150,10.0.1.179,10.0.1.153
      # Enable/disable release checking (optional - defaults to true)
      - ENABLE_RELEASE_CHECK=false
      # Config backup directory (optional - defaults to /backups/)
      - CONFIG_BACKUP_DIR=/backups/
      # Gunicorn configuration (optional - defaults shown)
      - PORT=9395
      - WORKERS=${WORKERS:-1}
      - TIMEOUT=120
      - KEEPALIVE=2
      - MAX_REQUESTS=1000
      - MAX_REQUESTS_JITTER=50
      # Prometheus multiprocess configuration
      - PROMETHEUS_MULTIPROC_DIR=/tmp
      - ENABLE_METRICS=true
    ports:
      - "${PORT:-9395}:${PORT:-9395}"
    stdin_open: true
    tty: true

volumes:
  wargos-storage:
    driver: local
