{
 "title": "Wargos Alpha V1",
 "description": "This is for prometheus metrics from WLED instances running locally",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ip_address",
    "label": "IP Address",
    "query": {
     "query": "label_values(wargos_wled_instance_basic_info,ip)"
    }
   },
   {
    "name": "name",
    "label": "WLED Name",
    "query": {
     "query": "label_values(wargos_wled_instance_basic_info,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "LED State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Is On By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_state_on{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Is On By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_state_on{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LED State Brightness By IP Address",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_state_brightness{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LED State Brightness By Name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_state_brightness{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LED FPS By IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_fps_value{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LED FPS By Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_fps_value{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Segment Is On By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_segment_on_value{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Is On By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_segment_on_value{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Effect ID By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_segment_effect_id_value{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Effect ID By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_segment_effect_id_value{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Palette ID By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_segment_palette_id_value{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Palette ID By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_segment_palette_id_value{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Length By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_segment_length_value{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Length By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_segment_length_value{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Brightness By IP Address",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_segment_brightness_value{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Brightness By Name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_segment_brightness_value{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Intensity By IP Address",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_segment_intensity_value{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Intensity By Name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_segment_intensity_value{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Speed By IP Address",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_segment_speed_value{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment Speed By Name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_segment_speed_value{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment CCT By IP Address",
   "type": "gauge",
   "description": "Color temperature",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_segment_cct_value{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segment CCT By Name",
   "type": "gauge",
   "description": "Color temperature",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_segment_cct_value{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Sync Send State By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_sync_send_state{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sync Send State By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_sync_send_state{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sync Receive State By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_sync_receive_state{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sync Receive State By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_sync_receive_state{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "LED Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "LED Count By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_led_count_value{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LED Count By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_led_count_value{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Uptime By IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_uptime_seconds{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uptime By Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_uptime_seconds{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Power Usage By IP Address",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_current_power{ip=~\"$ip_address\"})/max by (ip) (wargos_wled_instance_max_power{ip=~\"$ip_address\"}) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Usage By Name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_current_power{name=~\"$name\"})/max by (name) (wargos_wled_instance_max_power{name=~\"$name\"}) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Historical Power Usage By IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_current_power{ip=~\"$ip_address\"})/max by (ip) (wargos_wled_instance_max_power{ip=~\"$ip_address\"}) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Historical Power Usage By Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_current_power{name=~\"$name\"})/max by (name) (wargos_wled_instance_max_power{name=~\"$name\"}) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power By IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_max_power{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}} Max Power"
    },
    {
     "expr": "max by (ip) (wargos_wled_instance_current_power{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}} Current Power"
    }
   ]
  },
  {
   "title": "Power By Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_max_power{name=~\"$name\"})",
     "legendFormat": "{{name}} Max Power"
    },
    {
     "expr": "max by (name) (wargos_wled_instance_current_power{name=~\"$name\"})",
     "legendFormat": "{{name}} Current Power"
    }
   ]
  },
  {
   "title": "Power Clearance By IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_max_power{ip=~\"$ip_address\"}) - max by (ip) (wargos_wled_instance_current_power{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Clearance By Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_max_power{name=~\"$name\"}) - max by (name) (wargos_wled_instance_current_power{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max Power By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_max_power{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max Power By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_max_power{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current Power By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_current_power{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current Power By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_current_power{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Free Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 174 } },
  {
   "title": "Free Heap By IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_free_heap{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Free Heap By Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_free_heap{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "WiFi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 } },
  {
   "title": "WiFi RSSI by IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_wifi_rssi{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WiFi RSSI by Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_wifi_rssi{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WiFi Signal by IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (ip) (wargos_wled_instance_wifi_signal{ip=~\"$ip_address\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WiFi Signal by Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (name) (wargos_wled_instance_wifi_signal{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nightlight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nightlight Is On By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (ip) (wargos_wled_instance_nightlight_on_value{ip=~\"$ip_address\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nightlight Is On By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (name) (wargos_wled_instance_nightlight_on_value{name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nightlight Duration By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (ip) (wargos_wled_instance_nightlight_duration_minutes{ip=~\"$ip_address\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nightlight Duration By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (name) (wargos_wled_instance_nightlight_duration_minutes{name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nightlight Target Brightness By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (ip) (wargos_wled_instance_nightlight_target_brightness_value{ip=~\"$ip_address\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nightlight Target Brightness By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (name) (wargos_wled_instance_nightlight_target_brightness_value{name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem Used % By IP Address",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100*(max by (ip) (wargos_wled_instance_filesystem_space_kb_used{ip=~\"$ip_address\"})/max by (ip) (wargos_wled_instance_filesystem_space_kb_total{ip=~\"$ip_address\"}))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem Used % By Name",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100*(max by (name) (wargos_wled_instance_filesystem_space_kb_used{name=~\"$name\"})/max by (name) (wargos_wled_instance_filesystem_space_kb_total{name=~\"$name\"}))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem Used Space By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (ip) (wargos_wled_instance_filesystem_space_kb_used{ip=~\"$ip_address\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem Used Space By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (name) (wargos_wled_instance_filesystem_space_kb_used{name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem Total Space By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (ip) (wargos_wled_instance_filesystem_space_kb_total{ip=~\"$ip_address\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem Total Space By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (name) (wargos_wled_instance_filesystem_space_kb_total{name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}