{
 "title": "Wargos WLED by IP Address",
 "description": "This is for prometheus metrics from WLED instances running locally, by IP address",
 "tags": [
  "esp32",
  "home-assistant",
  "homeassistant",
  "wled"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ip_address",
    "label": "IP Address",
    "query": {
     "query": "label_values(wargos_wled_instance_basic_info,ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "LED State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Is On By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wargos_wled_instance_state_on{ip=~\"$ip_address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LED State Brightness By IP Address",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wargos_wled_instance_state_brightness{ip=~\"$ip_address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LED FPS By IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "wargos_wled_instance_fps_value{ip=~\"$ip_address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Uptime By IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "wargos_wled_instance_uptime_seconds{ip=~\"$ip_address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "WiFi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "WiFi RSSI by IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "wargos_wled_instance_wifi_rssi{ip=~\"$ip_address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WiFi Signal by IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "wargos_wled_instance_wifi_signal{ip=~\"$ip_address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Power Usage By IP Address",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wargos_wled_instance_current_power{ip=~\"$ip_address\"}/wargos_wled_instance_max_power{ip=~\"$ip_address\"} * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Historical Power Usage By IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "wargos_wled_instance_current_power{ip=~\"$ip_address\"}/wargos_wled_instance_max_power{ip=~\"$ip_address\"} * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max Power By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wargos_wled_instance_max_power{ip=~\"$ip_address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current Power By IP Address",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wargos_wled_instance_current_power{ip=~\"$ip_address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power By IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "wargos_wled_instance_max_power{ip=~\"$ip_address\"}",
     "legendFormat": "{{name}} Max Power"
    },
    {
     "expr": "wargos_wled_instance_current_power{ip=~\"$ip_address\"}",
     "legendFormat": "{{name}} Current Power"
    }
   ]
  },
  {
   "title": "Power Clearance By IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "wargos_wled_instance_max_power{ip=~\"$ip_address\"} - wargos_wled_instance_current_power{ip=~\"$ip_address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segment Is On By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_on_value{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment Effect ID By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_effect_id_value{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment Palette ID By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_palette_id_value{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment Length By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_length_value{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment Brightness By IP Address",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_brightness_value{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment Intensity By IP Address",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_intensity_value{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment Speed By IP Address",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_speed_value{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment CCT By IP Address",
     "type": "gauge",
     "description": "Color temperature",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_cct_value{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Send State By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_sync_send_state{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sync Receive State By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_sync_receive_state{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LED Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "LED Count By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_led_count_value{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nightlight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nightlight Is On By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_nightlight_on_value{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nightlight Duration By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_nightlight_duration_minutes{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nightlight Target Brightness By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_nightlight_target_brightness_value{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Free Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Heap By IP Address",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "wargos_wled_instance_free_heap{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem Used % By IP Address",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100*(wargos_wled_instance_filesystem_space_kb_used{ip=~\"$ip_address\"}/wargos_wled_instance_filesystem_space_kb_total{ip=~\"$ip_address\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem Used Space By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_filesystem_space_kb_used{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem Total Space By IP Address",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_filesystem_space_kb_total{ip=~\"$ip_address\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}