{
 "title": "Wargos WLED by Name",
 "description": "This is for prometheus metrics from WLED instances running locally, by name",
 "tags": [
  "wled",
  "home-assistant",
  "homeassistant",
  "esp32"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "WLED Name",
    "query": {
     "query": "label_values(wargos_wled_instance_basic_info,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "LED State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Is On By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wargos_wled_instance_state_on{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LED State Brightness By Name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wargos_wled_instance_state_brightness{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LED FPS By Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "wargos_wled_instance_fps_value{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Uptime By Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "wargos_wled_instance_uptime_seconds{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "WiFi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "WiFi RSSI by Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "wargos_wled_instance_wifi_rssi{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WiFi Signal by Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "wargos_wled_instance_wifi_signal{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Power Usage By Name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wargos_wled_instance_current_power{name=~\"$name\"}/wargos_wled_instance_max_power{name=~\"$name\"} * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Historical Power Usage By Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "wargos_wled_instance_current_power{name=~\"$name\"}/wargos_wled_instance_max_power{name=~\"$name\"} * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max Power By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wargos_wled_instance_max_power{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current Power By Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wargos_wled_instance_current_power{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power By Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "wargos_wled_instance_max_power{name=~\"$name\"}",
     "legendFormat": "{{name}} Max Power"
    },
    {
     "expr": "wargos_wled_instance_current_power{name=~\"$name\"}",
     "legendFormat": "{{name}} Current Power"
    }
   ]
  },
  {
   "title": "Power Clearance By Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "wargos_wled_instance_max_power{name=~\"$name\"} - wargos_wled_instance_current_power{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segment Is On By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_on_value{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment Effect ID By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_effect_id_value{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment Palette ID By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_palette_id_value{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment Length By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_length_value{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment Brightness By Name",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_brightness_value{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment Intensity By Name",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_intensity_value{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment Speed By Name",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_speed_value{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Segment CCT By Name",
     "type": "gauge",
     "description": "Color temperature",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_segment_cct_value{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Send State By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_sync_send_state{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sync Receive State By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_sync_receive_state{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LED Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "LED Count By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_led_count_value{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nightlight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nightlight Is On By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_nightlight_on_value{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nightlight Duration By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_nightlight_duration_minutes{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nightlight Target Brightness By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_nightlight_target_brightness_value{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Free Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Heap By Name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "wargos_wled_instance_free_heap{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem Used % By Name",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100*(wargos_wled_instance_filesystem_space_kb_used{name=~\"$name\"}/wargos_wled_instance_filesystem_space_kb_total{name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem Used Space By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_filesystem_space_kb_used{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem Total Space By Name",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "wargos_wled_instance_filesystem_space_kb_total{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}